name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Jest
      uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn test
        jestArgs: /sum.test.js
