name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Jest
      with:
          node-version: '16.14.0'
          cache: 'npm'
    - run: npm install
    - run: npm install -g jest
    - run: npm run unit-tests
        
